title: Marc Leroy - Robotics Engineer
author: Marc Leroy
email: marc.leroy93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marc Leroy is a cool guy who has a background in Robotics. 
  He graduated from EPFL in Switzerland, did research at NASA
  and currently works as a Hardware Engineer at Pix4D, a spin-off
  from his university which is known worldwide for its expertise
  in photogrammetry.

# social links
github_username:  maleroy

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
